apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-demo-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL : "https://github.com/mi-touch/devops_demo_project"
    targetRevision: HEAD
    path: ops-devops-project-time-printer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      