image:
  repository: mitouch/devops_demo_project
  tag: 9d6a2e4
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false